basePath: /
definitions:
  handlers.ErrorResponse:
    properties:
      code:
        type: integer
      fieldsErrors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:3001
info:
  contact: {}
  description: API Server for CRUD Application
  title: CRUD App API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authorize
      operationId: authorize
      parameters:
      - description: login params
        in: body
        name: inputBody
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Login
      tags:
      - auth
swagger: "2.0"
